name: llm-langchain
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - mkdocs=1.6.1
  - mkdocs-material=9.5.39
  - pymdown-extensions=10.11.1
  - pygments=2.18.0
  - pip
  - pip:
      - mkdocs-mermaid2-plugin>=1.2.0  # Actualizado a la última versión disponible